export type Product = {
  id: string;
  name: string;
  slug: string;
  category: string;
  categorySlug: string;
  brand: string;
  price: number;
  salePrice?: number;
  stock: number;
  sku: string;
  volume: string;
  weight: string;
  status: "active" | "draft";
  image: string;
  gallery: string[];
  shortDescription: string;
  description: string;
  richDescription: string;
  featured?: boolean;
  bestSeller?: boolean;
  isNew?: boolean;
  rating: number;
  reviews: number;
  notes: string[];
};
